# Generated by Django 5.2.9 on 2026-01-03 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_notification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
